### ISSUE TITLE
How is this going?

### ISSUE THREAD

**Issue by gwhizoftv** [acaranta/docker-minecraft-client#1]
This looks very cool. Is it runnable yet? How do I try it?

**Comment by vitorneto** [comment]
Hi this is great.
Do you have a more detailed information on how to connect using a web browser and vnc? i am trying to test this on a school on the chromebooks
many thanks

**Comment by acaranta** [comment]
I finally added some doc to the readme doc 🙈 
Sorry for being so late ... but once again this was juste a test, initially ^^

**Comment by vitorneto** [comment]
Hi Thank you for letting me know.Have a good dayVitor Fernandes-NetoOn 14 May 2023, at 09:26, Arthur Caranta ***@***.***> wrote:﻿
I finally added some doc to the readme doc 🙈
Sorry for being so late ... but once again this was juste a test, initially ^^
